# Generated by Django 3.1.5 on 2021-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('strength', models.CharField(max_length=3)),
                ('agility', models.CharField(max_length=3)),
                ('intelligence', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
