# Generated by Django 3.1.5 on 2021-01-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0002_auto_20210114_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='image',
            field=models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/7/7a/Strength_attribute_symbol.png/revision/latest/scale-to-width-down/40?cb=20180323111829', max_length=300),
        ),
    ]
