# Generated by Django 3.1.5 on 2021-01-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0003_heroes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_image', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/f/f6/Observer_Ward_icon.png/revision/latest/scale-to-width-down/100?cb=20160530171901')),
                ('cost', models.CharField(max_length=3)),
                ('bought_from', models.CharField(max_length=30)),
                ('initial_stock', models.CharField(max_length=3)),
                ('max_stock', models.CharField(max_length=3)),
                ('restock_time', models.CharField(max_length=3)),
                ('charges', models.CharField(max_length=3)),
                ('disassemble', models.BooleanField()),
                ('alert_allies', models.BooleanField()),
            ],
        ),
    ]
