# Generated by Django 3.1.5 on 2021-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0004_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_image', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/5/52/Tower_Protection_icon.png/revision/latest/scale-to-width-down/128?cb=20160426211855')),
                ('radius', models.CharField(max_length=5)),
                ('duration', models.FloatField(max_length=6)),
                ('ability', models.CharField(max_length=100)),
                ('affects', models.CharField(max_length=100)),
            ],
        ),
    ]
