# Generated by Django 3.1.5 on 2021-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0005_buildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_banner', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6c/Main_Page_Giant_Banner_New_Bloom_2020.jpg/revision/latest/scale-to-width-down/800?cb=20200124152923')),
                ('event_date', models.DateField()),
            ],
        ),
    ]
