# Generated by Django 3.1.5 on 2021-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0005_weeklyform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeeklyForm',
            new_name='WeeklyPolls',
        ),
    ]
