# Generated by Django 3.1.2 on 2021-01-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0006_auto_20210118_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_image', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/5/52/Tower_Protection_icon.png/revision/latest/scale-to-width-down/128?cb=20160426211855')),
                ('radius', models.CharField(max_length=5)),
                ('duration', models.FloatField(max_length=6)),
                ('ability', models.CharField(max_length=100)),
                ('affects', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_banner', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/6/6c/Main_Page_Giant_Banner_New_Bloom_2020.jpg/revision/latest/scale-to-width-down/800?cb=20200124152923')),
                ('event_date', models.DateField()),
            ],
        ),
    ]
