# Generated by Django 3.1.5 on 2021-01-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotabase', '0006_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_name', models.CharField(max_length=100)),
                ('icon', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/c/c9/Bounty_Rune_minimap_icon.png/revision/latest/scale-to-width-down/32?cb=20150121151359')),
                ('model', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/0/09/Rune_of_Bounty_model.png/revision/latest/scale-to-width-down/88?cb=20161214004322')),
                ('bottle', models.URLField(default='https://static.wikia.nocookie.net/dota2_gamepedia/images/c/ce/Bottle_%28Bounty%29_icon.png/revision/latest/scale-to-width-down/88?cb=20170529213537')),
                ('initial_gold', models.CharField(max_length=6)),
                ('extra_gold', models.CharField(max_length=6)),
            ],
        ),
    ]
